# Generated by Django 4.0.2 on 2022-05-25 15:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=255, verbose_name='Отчество')),
                ('login', models.CharField(max_length=255, verbose_name='Логин')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('passwd', models.CharField(max_length=64, verbose_name='Хеш пароля')),
                ('qrcode', models.FilePathField(verbose_name='Путь до QR кода')),
                ('create_date', models.DateTimeField(default=datetime.datetime.now(), verbose_name='Дата и время создания аккаунта')),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=255, verbose_name='Отчество')),
                ('group', models.CharField(max_length=255, verbose_name='Группа')),
                ('qrcode', models.FilePathField(verbose_name='Путь до QR кода')),
                ('create_date', models.DateTimeField(default=datetime.datetime.now(), verbose_name='Дата и время создания аккаунта')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.leader')),
            ],
        ),
    ]
