# Generated by Django 4.0.2 on 2022-05-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('group', models.CharField(max_length=90, verbose_name='Группа')),
                ('name', models.CharField(max_length=255, verbose_name='Ф. И. О.')),
            ],
            options={
                'verbose_name': 'Состав',
                'verbose_name_plural': 'Список состава',
            },
        ),
        migrations.CreateModel(
            name='enter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('group', models.CharField(max_length=90, verbose_name='Группа')),
                ('name', models.CharField(max_length=255, verbose_name='Ф. И. О.')),
                ('path_to_img', models.FilePathField(verbose_name='Путь до Изображения с камеры')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
            ],
            options={
                'verbose_name': 'Инфо о прохождении',
                'verbose_name_plural': 'Инфо о прохождениях',
            },
        ),
    ]
